app:
  env: "dev"
  name: "your-app-name"
  log:
    path: "/path/to/your/log/file.log"
    maxSize: 100
    maxAge: 60
  pagination:
    defaultSize: 20
    maxSize: 100
database:
  master:
    type: "mysql"
    dsn: "your-db-user:your-db-password@tcp(your-db-host:your-db-port)/your-db-name?charset=utf8mb4&parseTime=True&loc=Local"
    maxOpen: 100
    maxIdle: 10
    maxLifeTime: 60
  slave:
    type: "mysql"
    dsn: "your-db-user:your-db-password@tcp(your-db-host:your-db-port)/your-db-name?charset=utf8mb4&parseTime=True&loc=Local"
    maxOpen: 100
    maxIdle: 10
    maxLifeTime: 60
redis:
  addr: "your-redis-host:your-redis-port"
  password: "your-redis-password"
  poolSize: 10
  db: 0